/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DAO_Project;
import java.awt.Color;
import java.util.List;
import model.Model_Project;
import service.Service_Project;
import tablemodel.TabMod_Project;

/**
 *
 * @author rafii
 */
public class Data_Project extends javax.swing.JDialog {

    /**
     * Creates new form Group_Type1
     */
    private Service_Project service = (Service_Project) new DAO_Project();
    private TabMod_Project tblMod =  new TabMod_Project();
    public Model_Project model = new Model_Project();
    public boolean isDataSelected = false;
    public Data_Project(java.awt.Frame parent, boolean modal) {
        initComponents();
////        setBackground(new Color(0,0,0,0));
////        jTable1.getTableHeader().setOpaque(true);
//        jTable1.getTableHeader().setBackground(new Color(255,0,51));
////        jTable1.getTableHeader().setForeground(new Color(255,255,255));
        jTable1.setModel(tblMod);
        jTable1.setRowHeight(25);
        loadData();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDialog = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Group"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pDialog.setBackground(new java.awt.Color(255, 255, 255));
        pDialog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pDialog.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 50));

        t_search.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        t_search.setText("Search");
        t_search.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        t_search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_searchFocusLost(evt);
            }
        });
        t_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_searchMouseClicked(evt);
            }
        });
        t_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_searchActionPerformed(evt);
            }
        });
        t_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_searchKeyReleased(evt);
            }
        });
        pDialog.add(t_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, 50));

        jTable1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAlignmentX(1.0F);
        jTable1.setAlignmentY(1.0F);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pDialog.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 122, 551, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pDialog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Data Project");
        pDialog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 18, 150, 32));

        getContentPane().add(pDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 585, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_searchActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void t_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_searchMouseClicked
        
    }//GEN-LAST:event_t_searchMouseClicked

    private void t_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_searchFocusGained
        if(t_search.getText().contains("Search")){
            t_search.setText("");
        }
    }//GEN-LAST:event_t_searchFocusGained

    private void t_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_searchFocusLost
        if(t_search.getText().isEmpty()){
            t_search.setText("Search");
        }
    }//GEN-LAST:event_t_searchFocusLost

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void t_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_searchKeyPressed

    }//GEN-LAST:event_t_searchKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) { // Ganti 2 jika ingin satu klik
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            chooseData(); // Panggil hanya kalau baris valid
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void t_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_searchKeyReleased
        if(!t_search.getText().trim().isEmpty()){
            search();        
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_t_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Data_Project dialog = new Data_Project(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pDialog;
    private javax.swing.JTextField t_search;
    // End of variables declaration//GEN-END:variables
    private void search(){
        List<Model_Project>list=service.search(t_search.getText());
        tblMod.setData(list);
    }
    private void loadData(){
        List<Model_Project>list=service.getData();
        tblMod.setData(list);
    }
 
    private void chooseData() {
int row = jTable1.getSelectedRow();
    if (row != -1) {
model.setId_project(jTable1.getValueAt(row, 1).toString());
model.setProject_name(jTable1.getValueAt(row, 3).toString());
        dispose();
    }}
}
