package view;


import dao.DAO_Login;
import javax.swing.JOptionPane;
import main.Menu_utama;
import main.Menu_utama;
import model.Model_Group;
import model.Model_Karyawan;
import model.Model_Login;
import service.Service_Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rafii
 */
public class Form_Regist extends javax.swing.JFrame {
    int xx,xy;
    
    private Service_Login service = new DAO_Login();

    public Form_Regist() {
        initComponents();
        setLocationRelativeTo(this);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        iShowPw = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        tfPw = new javax.swing.JPasswordField();
        lblUser = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        iUser = new javax.swing.JLabel();
        iUser1 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        tfIdKry = new javax.swing.JTextField();
        lblPw1 = new javax.swing.JLabel();
        iUser2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblPti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, -1));

        iShowPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show.png"))); // NOI18N
        iShowPw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iShowPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iShowPwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iShowPwMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iShowPwMousePressed(evt);
            }
        });
        jPanel1.add(iShowPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 30));

        tfUser.setToolTipText("");
        jPanel1.add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, 30));

        tfPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPwActionPerformed(evt);
            }
        });
        tfPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPwKeyPressed(evt);
            }
        });
        jPanel1.add(tfPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 190, 30));

        lblUser.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Username");
        lblUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblUser.setInheritsPopupMenu(false);
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 20));

        lblPw.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblPw.setForeground(new java.awt.Color(255, 255, 255));
        lblPw.setText("ID Karyawan");
        jPanel1.add(lblPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, 30));

        iUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/locked.png"))); // NOI18N
        jPanel1.add(iUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, 30));

        iUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel1.add(iUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg-login.png"))); // NOI18N
        jPanel1.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 150, 310));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log-in.png"))); // NOI18N
        jPanel1.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 310));

        btnSignUp.setBackground(new java.awt.Color(102, 255, 255));
        btnSignUp.setText("Sign-up");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 90, -1));

        tfIdKry.setToolTipText("");
        jPanel1.add(tfIdKry, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 190, 30));

        lblPw1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblPw1.setForeground(new java.awt.Color(255, 255, 255));
        lblPw1.setText("Password");
        jPanel1.add(lblPw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, 30));

        iUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel1.add(iUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 30));

        btnLogin.setBackground(new java.awt.Color(102, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, 30));

        lblPti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPti.setForeground(new java.awt.Color(255, 255, 255));
        lblPti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_PADICON.jpg"))); // NOI18N
        lblPti.setText("  Form Regist");
        lblPti.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblPti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        proccessRegist();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void tfPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPwActionPerformed

    private void iShowPwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iShowPwMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_iShowPwMousePressed

    private void iShowPwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iShowPwMouseEntered
       tfPw.setEchoChar((char)0);
    }//GEN-LAST:event_iShowPwMouseEntered

    private void iShowPwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iShowPwMouseExited
       tfPw.setEchoChar('*');
    }//GEN-LAST:event_iShowPwMouseExited

    private void tfPwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPwKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPwKeyPressed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked

    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Form_login fl = new Form_login();
        fl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */

    private boolean validationRegist(){
      boolean result = false;
      String username = tfUser.getText(); 
      String pass = new String(tfPw.getPassword());
      String idKry = tfIdKry.getText(); 
      if (username.trim().isEmpty() && pass.trim().isEmpty()){
        JOptionPane.showMessageDialog(null,"Username & Password is required");
      }
        else if (username.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Username is required");
      } else if (pass.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Password is required");
      }else if (idKry.trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"ID Karyawan is required");
      }else{
            result = true;      
      }    
        return result;
    };
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Regist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel iShowPw;
    private javax.swing.JLabel iUser;
    private javax.swing.JLabel iUser1;
    private javax.swing.JLabel iUser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPti;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPw1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField tfIdKry;
    private javax.swing.JPasswordField tfPw;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables

    private void proccessRegist() {
        if(validationRegist()){
            view.Mst_Project mp = new Mst_Project();
            String username = tfUser.getText();
            String pass = new String(tfPw.getPassword());
            String idKry = tfIdKry.getText();
            model.Model_Login mod_log = new Model_Login();
            model.Model_Group mod_group = new Model_Group();
            model.Model_Karyawan mod_kry = new Model_Karyawan();
            mod_log.setUsername(username);
            mod_log.setPassword(pass);
            mod_group.setId_group("G-STF");
            mod_group.setGroup_name("Staff");
            mod_log.setMogr(mod_group);
//            mod_log.setMogr(mod_group).setId_Group("G-SPA");
            mod_kry.setId_karyawan(idKry);
//            mod_kry.setGroup_name("Super Admin");
            mod_log.setMokr(mod_kry);
            mod_log.setCreated_by(username);
            mod_log.setCreated_date(mp.getCurrentDateTime());
            mod_log.setUpdated_date(mp.getCurrentDateTime());
            mod_log.setLast_active(mp.getCurrentDateTime());
            mod_log.setUpdated_by("Super Admin");
//            mod_log.setId_karyawan(mp.generateSmartId("KRY-"));
            Form_login fl = new Form_login();
            Form_Regist fr = new Form_Regist();
            service.registLogin(mod_log,fl,fr);
            tfUser.setText("");
            tfPw.setText("");
            tfIdKry.setText("");
            dispose();
        }
    }

    
}
