/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import dao.DAO_Project;
import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Project;
import model.Model_Vendor;
import service.Service_Project;
import tablemodel.TabMod_Project;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author rafii
 */
public class Mst_Project extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private Service_Project service = (Service_Project) new DAO_Project();
    private TabMod_Project tblMod = new TabMod_Project();
    
    public Mst_Project() {
        initComponents();
        dataProjectTable.setModel(tblMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataProject = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataProjectTable = new javax.swing.JTable();
        addProject = new javax.swing.JPanel();
        titleProject = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ProjectSite = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbPm = new javax.swing.JComboBox<>();
        ProjectName = new javax.swing.JTextField();
        cbVendor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbSp = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        saveAddProject = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataProject.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Project");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn);

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(111, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(111, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn);

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataProjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataProjectTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataProjectTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataProjectTable.getTableHeader().setReorderingAllowed(false);
        dataProjectTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataProjectTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataProjectTableFocusLost(evt);
            }
        });
        dataProjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataProjectTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataProjectTable);

        javax.swing.GroupLayout dataProjectLayout = new javax.swing.GroupLayout(dataProject);
        dataProject.setLayout(dataProjectLayout);
        dataProjectLayout.setHorizontalGroup(
            dataProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataProjectLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(dataProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataProjectLayout.setVerticalGroup(
            dataProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataProjectLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataProject, "card2");

        addProject.setBackground(new java.awt.Color(255, 255, 255));

        titleProject.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleProject.setText("Add Project");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel3.setText("Project Name");

        ProjectSite.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel4.setText("Project Site");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel5.setText("Vendor Name");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel6.setText("Project Manager");

        cbPm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose Project Manager --", "Henis wido", "Herry" }));
        cbPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPmActionPerformed(evt);
            }
        });

        ProjectName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        cbVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVendorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel7.setText("Status Project");

        cbSp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose Status Project --", "Ongoing", "Completed" }));
        cbSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectSite)
                    .addComponent(ProjectName)
                    .addComponent(cbVendor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPm, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbSp, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectSite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        saveAddProject.setBackground(new java.awt.Color(102, 255, 0));
        saveAddProject.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        saveAddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        saveAddProject.setText("Save");
        saveAddProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddProjectActionPerformed(evt);
            }
        });
        jPanel2.add(saveAddProject);

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton5.setText("Cancel");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        javax.swing.GroupLayout addProjectLayout = new javax.swing.GroupLayout(addProject);
        addProject.setLayout(addProjectLayout);
        addProjectLayout.setHorizontalGroup(
            addProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addProjectLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(addProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        addProjectLayout.setVerticalGroup(
            addProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProjectLayout.createSequentialGroup()
                .addComponent(titleProject, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(addProject, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataProject);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPmActionPerformed

    private void cbVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVendorActionPerformed

    private void saveAddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddProjectActionPerformed
       if(titleProject.getText().equals("Add Project")){
            saveData();
       }else if(titleProject.getText().equals("Edit Project")){
            updateData();
       }
    }//GEN-LAST:event_saveAddProjectActionPerformed

    private void dataProjectTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataProjectTableMouseClicked

    }//GEN-LAST:event_dataProjectTableMouseClicked

    private void dataProjectTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataProjectTableFocusLost

    }//GEN-LAST:event_dataProjectTableFocusLost

    private void dataProjectTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataProjectTableFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_dataProjectTableFocusGained

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        titleProject.setText("Edit Project");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addProject);
        mainPanel.repaint();
        mainPanel.revalidate();
        getDataTable();
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        delData();
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        titleProject.setText("Add Project");
        resetForm();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addProject);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_addBtnActionPerformed

    private void cbSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSpActionPerformed
    private void saveData() {
        if(inputValidation()){
            String pn = ProjectName.getText();
            String ps = ProjectSite.getText();
            String pv = (String) cbVendor.getSelectedItem();
            String pm = (String) cbPm.getSelectedItem();
            String sp = (String) cbSp.getSelectedItem();
            
            
            Model_Project mp = new Model_Project();
            Model_Vendor mv = new Model_Vendor();
            mp.setId_project(generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            mp.setProject_manager(pm);
            mp.setProject_name(pn);
            mp.setStatus(sp);
            mp.setProject_site(ps);  
            List<Model_Project> listVendor = service.getDataVendor();
            for (Model_Project project : listVendor) {
                    if(project.getMovr().getVendor_name().toString().equals(pv)){
                        mv.setId_vendor(project.getMovr().getId_vendor().toString());
                        mp.setMovr(mv);
                       
                        
                    }
                }
            mp.setSts_active("1");
            mp.setCreated_date(getCurrentDateTime());
            mp.setUpdated_date(getCurrentDateTime());
            mp.setUpdated_by("Admin");
            mp.setCreated_by("Admin");
//            System.out.print((String)generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            service.addData(mp);
            tblMod.addData(mp);
            resetForm();
            loadData();
            showPanel();
        }
    }
    public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }
    public String getFourthChar(String text) {
        if (text != null && text.length() >= 4) {
          return String.valueOf(text.charAt(3)); // huruf ke-4 (indeks ke-3)
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
        }
    }
    private boolean inputValidation(){
        boolean result = false;
        if(ProjectName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Project Name is Required!");
        }else if(ProjectSite.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Project Site is Required!");
        }else if(cbVendor.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Vendor Name is Required!");
        }else if(cbPm.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Project Manager is Required!");
        }else if(cbSp.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Status Project is Required!");
        }else{
            result = true;
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ProjectName;
    private javax.swing.JTextField ProjectSite;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addProject;
    private javax.swing.JComboBox<String> cbPm;
    private javax.swing.JComboBox<String> cbSp;
    private javax.swing.JComboBox<String> cbVendor;
    private javax.swing.JPanel dataProject;
    private javax.swing.JTable dataProjectTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton saveAddProject;
    private javax.swing.JLabel titleProject;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        List<Model_Project> list = service.getData();
        List<Model_Project> listVendor = service.getDataVendor();
        tblMod.setData(list);
        mainPanel.revalidate();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- Choose Vendor --");

    // Tambahkan nama vendor ke model
    for (Model_Project project : listVendor) {
        model.addElement(project.getMovr().getVendor_name().toString());
    }
    
    // Set model ke JComboBox
    cbVendor.setModel(model);
    }
    public String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }

    private void resetForm() {
        ProjectName.setText("");
        ProjectSite.setText("");
        cbVendor.setSelectedIndex(0);
        cbPm.setSelectedIndex(0);
        cbSp.setSelectedIndex(0);
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Mst_Project());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void getDataTable() {
        int row = dataProjectTable.getSelectedRow();
        ProjectName.setText(dataProjectTable.getModel().getValueAt(row, 3).toString());
        ProjectSite.setText(dataProjectTable.getModel().getValueAt(row, 4).toString());
        cbVendor.setSelectedItem((String) dataProjectTable.getModel().getValueAt(row, 5).toString());
        cbPm.setSelectedItem((String) dataProjectTable.getModel().getValueAt(row, 2).toString());
        cbSp.setSelectedItem((String) dataProjectTable.getModel().getValueAt(row, 6).toString());
        
    }
    
    private void updateData() {
        int index = dataProjectTable.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
                String ip = dataProjectTable.getModel().getValueAt(index, 1).toString();
                String pn = ProjectName.getText();
                String ps = ProjectSite.getText();
                String pv = (String) cbVendor.getSelectedItem();
                String pm = (String) cbPm.getSelectedItem();
                String sp = (String) cbSp.getSelectedItem();
                Model_Vendor mv = new Model_Vendor();
                Model_Project mp = new Model_Project();
                
                List<Model_Project> listVendor = service.getDataVendor();
                for (Model_Project project : listVendor) {
                    if(project.getMovr().getVendor_name().toString().equals(pv)){
                        mv.setId_vendor(project.getMovr().getId_vendor().toString());
                        mp.setMovr(mv);
                       
                        
                    }
                }
                mp.setId_project(ip);
                mp.setStatus(sp);
                mp.setProject_manager(pm);
                mp.setProject_name(pn);
                mp.setProject_site(ps);
                mp.setUpdated_date(getCurrentDateTime());
                mp.setUpdated_by("Admin");
                service.updateData(mp);
                tblMod.updateData(index, mp);
                loadData();
                showPanel();
            }
        }
    }

    private void delData() {
        int index = dataProjectTable.getSelectedRow();
        if(index!=-1){
            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(modPro);
                tblMod.deleteData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }
    
}
