/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import dao.DAO_Vendor;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Project;
import model.Model_Vendor;
import service.Service_Vendor;
import tablemodel.TabMod_Vendor;

/**
 *
 * @author rafii
 */
public class Mst_Vendor extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private Service_Vendor service = (Service_Vendor) new DAO_Vendor();
    private TabMod_Vendor tblMod = new TabMod_Vendor();
    
    
    public Mst_Vendor() {
        initComponents();
        dataVendorTable.setModel(tblMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataVendor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataVendorTable = new javax.swing.JTable();
        addVendor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataVendor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Vendor");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn);

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(111, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(111, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn);

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataVendorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataVendorTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataVendorTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataVendorTable.getTableHeader().setReorderingAllowed(false);
        dataVendorTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataVendorTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataVendorTableFocusLost(evt);
            }
        });
        dataVendorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataVendorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataVendorTable);

        javax.swing.GroupLayout dataVendorLayout = new javax.swing.GroupLayout(dataVendor);
        dataVendor.setLayout(dataVendorLayout);
        dataVendorLayout.setHorizontalGroup(
            dataVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataVendorLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(dataVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(473, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataVendorLayout.setVerticalGroup(
            dataVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataVendorLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataVendor, "card2");

        addVendor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Vendor");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setBackground(new java.awt.Color(102, 255, 0));
        jButton4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        jButton4.setText("Save");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton5.setText("Cancel");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jLabel7.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel7.setText("Vendor Name");

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel5.setText("Location");

        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel6.setText("No.Telp");

        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel8.setText("Pic Vendor");

        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addVendorLayout = new javax.swing.GroupLayout(addVendor);
        addVendor.setLayout(addVendorLayout);
        addVendorLayout.setHorizontalGroup(
            addVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVendorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(addVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField6)
                    .addGroup(addVendorLayout.createSequentialGroup()
                        .addGroup(addVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addVendorLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(addVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        addVendorLayout.setVerticalGroup(
            addVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVendorLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        mainPanel.add(addVendor, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataVendor);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed
        jLabel2.setText("Edit Vendor");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addVendor);
        mainPanel.repaint();
        mainPanel.revalidate();  
        getDataTable();// TODO add your handling code here:
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
     delData();  // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        jLabel2.setText("Add Vendor");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addVendor);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_addBtnActionPerformed

    private void dataVendorTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVendorTableFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_dataVendorTableFocusGained

    private void dataVendorTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVendorTableFocusLost

    }//GEN-LAST:event_dataVendorTableFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jLabel2.getText().equals("Add Vendor")){
             saveData(); // TODO add your handling code here:
       }else if(jLabel2.getText().equals("Edit Vendor")){
            updateData();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void dataVendorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataVendorTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataVendorTableMouseClicked
    private void saveData() {
        if(inputValidation()){
            
            String vn = jTextField2.getText();
            String l = jTextField3.getText();
            String nt = jTextField4.getText();
            String pv = jTextField6.getText();
            
            
            Model_Vendor mv = new Model_Vendor();
            mv.setId_vendor(generateSmartId("V-"));
            mv.setVendor_name(vn);
            mv.setLocation(l);
            mv.setNo_telp(nt);
            mv.setPic_vendor(pv);            
              
            mv.setSts_active("1");
            mv.setCreated_date(getCurrentDateTime());
            mv.setUpdated_date(getCurrentDateTime());
            mv.setUpdated_by("Admin");
            mv.setCreated_by("Admin");
//            System.out.print((String)generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            service.addData(mv);
            tblMod.addData(mv);
            resetForm();
            loadData();
            showPanel();
        }
    }
    public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }
    public String getFourthChar(String text) {
        if (text != null && text.length() >= 4) {
          return String.valueOf(text.charAt(3)); // huruf ke-4 (indeks ke-3)
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
        }
    }
    private boolean inputValidation(){
        boolean result = false;
         if(jTextField2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Vendor Name is Required!");
        }else if(jTextField3.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Location is Required!");
        }else if(jTextField6.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Pic Vendor is Required!");
        }else{
            result = true;
        }
        return result;
    }

    private void getData(){
        DefaultTableModel tbm=new DefaultTableModel();
       
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addVendor;
    private javax.swing.JPanel dataVendor;
    private javax.swing.JTable dataVendorTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables
    private Mst_Project mp = new Mst_Project();
    public List<Model_Vendor> Change(){
        return null;
    }
    
    
    private void loadData() {
        List<Model_Vendor> list = service.getData();
        tblMod.setData(list);
        mainPanel.revalidate();
        
    }
    
     private void getDataTable() {
        int row = dataVendorTable.getSelectedRow();
        jTextField2.setText(dataVendorTable.getModel().getValueAt(row, 2).toString());
        jTextField3.setText(dataVendorTable.getModel().getValueAt(row, 3).toString());
        jTextField4.setText(dataVendorTable.getModel().getValueAt(row, 4).toString());
        jTextField6.setText(dataVendorTable.getModel().getValueAt(row, 5).toString());
    }
     
    private void resetForm() {
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Mst_Vendor());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    public String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }
    
    private void delData() {
        int index = dataVendorTable.getSelectedRow();
        if(index!=-1){
            Model_Vendor modPro = tblMod.getData(dataVendorTable.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(modPro);
                tblMod.deleteData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }
     private void updateData() {
        int index = dataVendorTable.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
            String iv = dataVendorTable.getModel().getValueAt(index, 1).toString();
            String vn = jTextField2.getText();
            String l = jTextField3.getText();
            String nt = jTextField4.getText();
            String pv = jTextField6.getText();
            
            
            Model_Vendor mv = new Model_Vendor();
            mv.setId_vendor(iv);
            mv.setVendor_name(vn);
            mv.setLocation(l);
            mv.setNo_telp(nt);
            mv.setPic_vendor(pv);            
              
            mv.setSts_active("1");
            mv.setCreated_date(getCurrentDateTime());
            mv.setUpdated_date(getCurrentDateTime());
            mv.setUpdated_by("Admin");
            mv.setCreated_by("Admin");
                
               
                service.updateData(mv);
                tblMod.updateData(index, mv);
                loadData();
                showPanel();
            }
        }
    }
}