package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import config.Koneksi;
import dao.DAO_User;
import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_User;
import model.Model_Karyawan;
import service.Service_User;
import tablemodel.TabMod_User;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import model.Model_Group;
import model.Model_Project;


/**
 *
 * @author rafii
 */
public class Mst_User extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private Service_User service = (Service_User) new DAO_User();
    private TabMod_User tblMod = new TabMod_User();
    
    public Mst_User() {
        initComponents();
        dataUserTable.setModel(tblMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataUserTable = new javax.swing.JTable();
        addUser = new javax.swing.JPanel();
        titleUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        tfPw = new javax.swing.JPasswordField();
        ck = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ck1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        saveAddProject = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data User");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn);

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(111, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(111, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn);

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataUserTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataUserTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataUserTable.getTableHeader().setReorderingAllowed(false);
        dataUserTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataUserTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataUserTableFocusLost(evt);
            }
        });
        dataUserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataUserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataUserTable);

        javax.swing.GroupLayout dataUserLayout = new javax.swing.GroupLayout(dataUser);
        dataUser.setLayout(dataUserLayout);
        dataUserLayout.setHorizontalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataUserLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(400, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataUserLayout.setVerticalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataUserLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataUser, "card2");

        addUser.setBackground(new java.awt.Color(255, 255, 255));

        titleUser.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleUser.setText("Add User");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel4.setText("Password");

        Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        tfPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPwActionPerformed(evt);
            }
        });

        ck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel5.setText("Karyawan");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel6.setText("Group");

        ck1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addComponent(tfPw)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ck1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        saveAddProject.setBackground(new java.awt.Color(102, 255, 0));
        saveAddProject.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        saveAddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        saveAddProject.setText("Save");
        saveAddProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddProjectActionPerformed(evt);
            }
        });
        jPanel2.add(saveAddProject);

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton5.setText("Cancel");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        javax.swing.GroupLayout addUserLayout = new javax.swing.GroupLayout(addUser);
        addUser.setLayout(addUserLayout);
        addUserLayout.setHorizontalGroup(
            addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addUserLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        addUserLayout.setVerticalGroup(
            addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserLayout.createSequentialGroup()
                .addComponent(titleUser, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(addUser, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataUser);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void saveAddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddProjectActionPerformed
       if(titleUser.getText().equals("Add User")){
            saveData();
       }else if(titleUser.getText().equals("Edit User")){
            updateData();
       }
    }//GEN-LAST:event_saveAddProjectActionPerformed

    private void dataUserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataUserTableMouseClicked

    }//GEN-LAST:event_dataUserTableMouseClicked

    private void dataUserTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataUserTableFocusLost

    }//GEN-LAST:event_dataUserTableFocusLost

    private void dataUserTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataUserTableFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_dataUserTableFocusGained

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        ck.setEnabled(false);
        tfPw.setEditable(false);
        Username.setEditable(false);
        titleUser.setText("Edit User");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addUser);
        mainPanel.repaint();
        mainPanel.revalidate();
        getDataTable();
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        delData();
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        ck.setEnabled(true);
        tfPw.setEditable(true);
        Username.setEditable(true);
        titleUser.setText("Add User");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addUser);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_addBtnActionPerformed

    private void tfPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPwActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void ckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckActionPerformed

    private void ck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck1ActionPerformed
    private void saveData() {
        if(inputValidation()){
            String pn = Username.getText();
            String ps = new String(tfPw.getPassword());
            String pv = (String) ck.getSelectedItem();
            String pv1 = (String) ck1.getSelectedItem();
            
            
            Model_User mp = new Model_User();
            Model_Group mp1 = new Model_Group();
            Model_Karyawan mv = new Model_Karyawan();
            mp.setUsername(pn);
            mp.setPassword(ps);
            
            List<Model_User> listKaryawan = service.getDataKaryawan();
            for (Model_User karyawan : listKaryawan) {
                    if(karyawan.getMovr().getNama_lengkap().toString().equals(pv)){
                        mp.setId_karyawan(karyawan.getMovr().getId_karyawan().toString());
                        mp.setMovr(mv);
                       
                        
                    }
                }
            List<Model_User> listGroup = service.getDataGroup();
            for (Model_User karyawan : listGroup) {
                    if(karyawan.getMogr().getGroup_name().toString().equals(pv1)){
                        mp1.setId_group(karyawan.getMogr().getId_group().toString());
                        mp.setMogr(mp1);
                       
                        
                    }
                }
            
            mp.setSts_active("1");
            mp.setCreated_date(getCurrentDateTime());
            mp.setUpdated_date(getCurrentDateTime());
            mp.setUpdated_by("Admin");
            mp.setCreated_by("Admin");
            mp.setLast_login(getCurrentDateTime());
//            System.out.print((String)generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            service.addData(mp);
            tblMod.addData(mp);
            resetForm();
            loadData();
            showPanel();
        }
    }
    public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }
    public String getFourthChar(String text) {
        if (text != null && text.length() >= 4) {
          return String.valueOf(text.charAt(3)); // huruf ke-4 (indeks ke-3)
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
        }
    }
    private boolean inputValidation(){
        boolean result = false;
        if(Username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"UserName is Required!");
        }else if(tfPw.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Password is Required!");
            }else if(ck.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Karyawan is Required!");
        }else{
            result = true;
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Username;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addUser;
    private javax.swing.JComboBox<String> ck;
    private javax.swing.JComboBox<String> ck1;
    private javax.swing.JPanel dataUser;
    private javax.swing.JTable dataUserTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton saveAddProject;
    private javax.swing.JPasswordField tfPw;
    private javax.swing.JLabel titleUser;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

     private void loadData() {
        List<Model_User> list = service.getData();
        List<Model_User> listKaryawan = service.getDataKaryawan();
        List<Model_User> listGroup = service.getDataGroup();
        tblMod.setData(list);
        mainPanel.revalidate();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- Pilih Karyawan --");

    // Tambahkan nama vendor ke model
    for (Model_User karyawan : listKaryawan) {
        model.addElement(karyawan.getMovr().getNama_lengkap().toString());
    }
    
    // Set model ke JComboBox
    ck.setModel(model);
            DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>();
        model1.addElement("-- Pilih Group --");

    // Tambahkan nama vendor ke model
    for (Model_User group : listGroup) {
        model1.addElement(group.getMogr().getGroup_name().toString());
    }
    
    // Set model ke JComboBox
    ck1.setModel(model1);
    }
    public String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }

    private void resetForm() {
        Username.setText("");
        tfPw.setText("");
        
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Mst_User());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void getDataTable() {
        int row = dataUserTable.getSelectedRow();
        Username.setText(dataUserTable.getModel().getValueAt(row, 3).toString());
        tfPw.setText(dataUserTable.getModel().getValueAt(row, 4).toString());
        ck.setSelectedItem((String) dataUserTable.getModel().getValueAt(row, 1).toString());
        ck1.setSelectedItem((String) dataUserTable.getModel().getValueAt(row, 2).toString());
        
    }
    
    private void updateData() {
        int index = dataUserTable.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
                String ip = dataUserTable.getModel().getValueAt(index, 3).toString();
                String pv1 = (String) ck1.getSelectedItem();
                String ps = tfPw.getText();
                
                Model_User mp = new Model_User();
                Model_Group mg = new Model_Group();
                List<Model_User> listGroup = service.getDataGroup();
            for (Model_User karyawan : listGroup) {
                    if(karyawan.getMogr().getGroup_name().toString().equals(pv1)){
                        mg.setId_group(karyawan.getMogr().getId_group().toString());
                        mp.setMogr(mg);
                       
                        
                    }
                }
                
                mp.setUsername(ip);
                mp.setPassword(ps);
                mp.setUpdated_date(getCurrentDateTime());
                mp.setUpdated_by("Super Admin");
                service.updateData(mp);
                tblMod.updateData(index, mp);
                loadData();
                showPanel();
            }
        }
    }

    private void delData() {
        int index = dataUserTable.getSelectedRow();
        if(index!=-1){
            Model_User modPro = tblMod.getData(dataUserTable.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(modPro);
                tblMod.deleteData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }
    
}
