/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DAO_Item;
import config.Koneksi;

import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Distributor;
import model.Model_Group;
import model.Model_Item;
import model.Model_Item;
import model.Model_Project;
import model.Model_Type;
import model.Model_Vendor;
import service.Service_Item;
import tablemodel.TabMod_Item;

/**
 *
 * @author rafii
 */
public class Mst_Item extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private final Service_Item service = (Service_Item) new DAO_Item();
    private final TabMod_Item tblMod = new TabMod_Item();
    
    public Mst_Item() {
        initComponents();
        dataItemTable.setModel(tblMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataItem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataItemTable = new javax.swing.JTable();
        addItem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfBrand = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        tfItemName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        cbUnit = new javax.swing.JComboBox<>();
        tfStock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        cbDst = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Bsave = new javax.swing.JButton();
        Bcancel = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataItem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Items");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn);

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(111, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(111, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn);

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataItemTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataItemTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataItemTable.getTableHeader().setReorderingAllowed(false);
        dataItemTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataItemTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataItemTableFocusLost(evt);
            }
        });
        dataItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataItemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataItemTable);

        javax.swing.GroupLayout dataItemLayout = new javax.swing.GroupLayout(dataItem);
        dataItem.setLayout(dataItemLayout);
        dataItemLayout.setHorizontalGroup(
            dataItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataItemLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(dataItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(315, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataItemLayout.setVerticalGroup(
            dataItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataItemLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataItem, "card2");

        addItem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Item");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel3.setText("Distributor");

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel5.setText("Items Name");

        tfBrand.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel6.setText("Brand");

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose Type --", "Pcs", "Meter", "Roll", "Lot" }));
        cbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeActionPerformed(evt);
            }
        });

        tfItemName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel8.setText("Unit");

        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        cbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose Unit --", "Pcs", "Meter", "Roll", "Lot" }));
        cbUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUnitActionPerformed(evt);
            }
        });

        tfStock.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStockActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel9.setText("Stock");

        tfPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceActionPerformed(evt);
            }
        });

        cbDst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose Type --", "Pcs", "Meter", "Roll", "Lot" }));
        cbDst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDstActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel10.setText("Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfBrand)
                    .addComponent(tfItemName)
                    .addComponent(jTextField6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbUnit, 0, 401, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStock, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPrice)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(274, 274, 274)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Bsave.setBackground(new java.awt.Color(102, 255, 0));
        Bsave.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Bsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        Bsave.setText("Save");
        Bsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });
        jPanel2.add(Bsave);

        Bcancel.setBackground(new java.awt.Color(255, 0, 51));
        Bcancel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Bcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        Bcancel.setText("Cancel");
        Bcancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelActionPerformed(evt);
            }
        });
        jPanel2.add(Bcancel);

        javax.swing.GroupLayout addItemLayout = new javax.swing.GroupLayout(addItem);
        addItem.setLayout(addItemLayout);
        addItemLayout.setHorizontalGroup(
            addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemLayout.createSequentialGroup()
                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addItemLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addItemLayout.setVerticalGroup(
            addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addItemLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        mainPanel.add(addItem, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataItem);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_BcancelActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed
        jLabel2.setText("Edit Item");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addItem);
        mainPanel.repaint();
        mainPanel.revalidate();
        getDataTable();// TODO add your handling code here:
        cbDst.setEnabled(false);
        cbType.setEnabled(false);

    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        delData();
    // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        jLabel2.setText("Add Item");
        resetForm();
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addItem);
        mainPanel.repaint();
        mainPanel.revalidate();
        cbDst.setEnabled(true);
        cbType.setEnabled(true);
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void dataItemTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataItemTableFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_dataItemTableFocusGained

    private void dataItemTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataItemTableFocusLost
    
    }//GEN-LAST:event_dataItemTableFocusLost

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed
        if(jLabel2.getText().equals("Add Item")){
            saveData();
       }else if(jLabel2.getText().equals("Edit Item")){
            updateData();
       }// TODO add your handling code here:
    }//GEN-LAST:event_BsaveActionPerformed

    private void dataItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataItemTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataItemTableMouseClicked

    private void tfItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemNameActionPerformed

    private void cbUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUnitActionPerformed

    private void tfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockActionPerformed

    private void tfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceActionPerformed

    private void cbDstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDstActionPerformed
    
    private void getData(){
        DefaultTableModel tbm=new DefaultTableModel();
       
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancel;
    private javax.swing.JButton Bsave;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addItem;
    private javax.swing.JComboBox<String> cbDst;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JComboBox<String> cbUnit;
    private javax.swing.JPanel dataItem;
    private javax.swing.JTable dataItemTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfItemName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfStock;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

    private void loadData() {

        List<Model_Item> list = service.getData();
        List<Model_Item> listDistributor = service.getDataDistributor();
        List<Model_Item> listGroup = service.getDataType();
        tblMod.setData(list);
        mainPanel.revalidate();
        cbDst.setEnabled(true);
        cbType.setEnabled(true);
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>();
        model.addElement("-- Choose Distributor --");
        model1.addElement("-- Choose Type --");

    // Tambahkan nama vendor ke model
        for (Model_Item distributor : listDistributor) {
            model.addElement(distributor.getModt().getDistributor_name().toString());
        }

        // Set model ke JComboBox
        cbDst.setModel(model);
        
        for (Model_Item group : listGroup) {
            model1.addElement(group.getMoty().getType_name().toString());
        }

        // Set model ke JComboBox
        cbType.setModel(model1);
    }

    private void getDataTable() {
        int row = dataItemTable.getSelectedRow();
        cbDst.setSelectedItem((String)dataItemTable.getModel().getValueAt(row, 4).toString());
        cbType.setSelectedItem((String)dataItemTable.getModel().getValueAt(row, 2).toString());
        cbUnit.setSelectedItem((String)dataItemTable.getModel().getValueAt(row, 5).toString());
        tfItemName.setText(dataItemTable.getModel().getValueAt(row, 3).toString());
        tfBrand.setText(dataItemTable.getModel().getValueAt(row, 8).toString());
        tfStock.setText(dataItemTable.getModel().getValueAt(row, 6).toString());
        tfPrice.setText(dataItemTable.getModel().getValueAt(row, 7).toString());
           
    }

    private void saveData() {
      if(inputValidation()){
            
            String d = (String) cbDst.getSelectedItem();
            String t = (String) cbType.getSelectedItem();
            String u = (String) cbUnit.getSelectedItem();
            String in = tfItemName.getText();
            String b = tfBrand.getText();
            String s = tfStock.getText();
            String p = tfPrice.getText();
            
            Model_Distributor md = new Model_Distributor();
            Model_Type mt = new Model_Type();
            Model_Item mi = new Model_Item();
            mi.setId_items(generateSmartId("IT-"+getTypeChar((String) cbType.getSelectedItem())+"-"));
            mt.setType_name(t);
            mi.setMoty(mt);
            mi.setUnit(u);
            mi.setItems_name(in);
            mi.setBrand(b);
            mi.setStock(s);
            mi.setPrice(p);
              
            mi.setStatus_active("1");
            mi.setCreated_date(getCurrentDateTime());
            mi.setUpdated_date(getCurrentDateTime());
            mi.setUpdated_by("Admin");
            mi.setCreated_by("Admin");
            List<Model_Item> listDistributor = service.getDataDistributor();
            List<Model_Item> listType = service.getDataType();
            for (Model_Item distributor : listDistributor) {
                    if(distributor.getModt().getDistributor_name().toString().equals(d)){
                        md.setId_distributor(distributor.getModt().getId_distributor().toString());
                        mi.setModt(md);
                       
                        
                    }
            }
            
            for (Model_Item type : listType) {
                    if(type.getMoty().getType_name().toString().equals(t)){
                        mt.setId_type(type.getMoty().getId_type().toString());
                        mi.setMoty(mt);
                       
                        
                    }
            }
//            System.out.print((String)generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            service.addData(mi);
            tblMod.addData(mi);
            resetForm();
            loadData();
            showPanel();
        }
    }  
    

    private void updateData() {
        int index = dataItemTable.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
            String id = dataItemTable.getModel().getValueAt(index, 1).toString();
             
            String d = (String)cbDst.getSelectedItem();
            String t = (String) cbType.getSelectedItem();
            String u = (String) cbUnit.getSelectedItem();
            String in = tfItemName.getText();
            String b = tfBrand.getText();
            String s = tfStock.getText();
            String p = tfPrice.getText();
            
            Model_Distributor md = new Model_Distributor();
            Model_Type mt = new Model_Type();
            Model_Item mi = new Model_Item();
            
             List<Model_Item> listDistributor = service.getDataDistributor();
            List<Model_Item> listType = service.getDataType();
            for (Model_Item distributor : listDistributor) {
                    if(distributor.getModt().getDistributor_name().toString().equals(d)){
                        md.setId_distributor(distributor.getModt().getId_distributor().toString());
                        mi.setModt(md);
                       
                        
                    }
            }
            
            for (Model_Item type : listType) {
                    if(type.getMoty().getType_name().toString().equals(t)){
                        mt.setId_type(type.getMoty().getId_type().toString());
                        mi.setMoty(mt);
                       
                        
                    }
            }
            mi.setId_items(id);
            mi.setUnit(u);
            mi.setItems_name(in);
            mi.setBrand(b);
            mi.setStock(s);
            mi.setPrice(p);  
            mi.setUpdated_date(getCurrentDateTime());
            mi.setUpdated_by("Admin");
            service.updateData(mi);
            tblMod.updateData(index, mi);
            loadData();
            showPanel();
            }
        }
    }    
    private boolean inputValidation() {
        boolean result = false;
         if(cbDst.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Distributor is Required!");
        }else if(cbType.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Group is Required!");
        }else if(cbUnit.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Unit is Required!");
        }else if(tfItemName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Item is Required!");
        }else if(tfBrand.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Brand is Required!");
        }else if(tfStock.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Stock is Required!");
        }else if(tfPrice.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Price is Required!");
        }else{
            result = true;
        }
        return result;
    }

    public String getTypeChar(String text) {
        if (text != null && text.length() >= 7) {
          return String.valueOf(text.charAt(6)); // huruf ke-7 
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
    }
    }

    public String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }

    private void resetForm() {
        cbDst.setSelectedIndex(0);
        cbType.setSelectedIndex(0);
        cbUnit.setSelectedIndex(0);
        tfItemName.setText("");
        tfBrand.setText("");
        tfStock.setText("");
        tfPrice.setText("");
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Mst_Item());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

   public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }

    private void delData() {
        int index = dataItemTable.getSelectedRow();
        if(index!=-1){
            Model_Item modPro = tblMod.getData(dataItemTable.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(modPro);
                tblMod.deleteData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }
}
