/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import dao.DAO_Distributor;
import dao.DAO_Group;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Distributor;
import model.Model_Group;
import model.Model_Vendor;
import service.Service_Distributor;
import service.Service_Group;
import tablemodel.TabMod_Distributor;
import tablemodel.TabMod_Group;

/**
 *
 * @author rafii
 */
public class Mst_Group extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private Service_Group service = (Service_Group) new DAO_Group();
    private TabMod_Group tblMod = new TabMod_Group();
    
    public Mst_Group() {
        initComponents();
        dataDistributorTable.setModel(tblMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataGroup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataDistributorTable = new javax.swing.JTable();
        addGroup = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfGroup = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataGroup.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Group");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn);

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(111, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(111, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn);

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataDistributorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataDistributorTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataDistributorTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataDistributorTable.getTableHeader().setReorderingAllowed(false);
        dataDistributorTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataDistributorTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataDistributorTableFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(dataDistributorTable);

        javax.swing.GroupLayout dataGroupLayout = new javax.swing.GroupLayout(dataGroup);
        dataGroup.setLayout(dataGroupLayout);
        dataGroupLayout.setHorizontalGroup(
            dataGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataGroupLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(dataGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataGroupLayout.setVerticalGroup(
            dataGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataGroupLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataGroup, "card2");

        addGroup.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Distributor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel3.setText("Id Group");

        tfId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfId.setEnabled(false);
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel4.setText("Group Name");

        tfGroup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tfGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGroup)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 810, Short.MAX_VALUE))
                    .addComponent(tfId))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setBackground(new java.awt.Color(102, 255, 0));
        jButton4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        jButton4.setText("Save");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton5.setText("Cancel");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        javax.swing.GroupLayout addGroupLayout = new javax.swing.GroupLayout(addGroup);
        addGroup.setLayout(addGroupLayout);
        addGroupLayout.setHorizontalGroup(
            addGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addGroupLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(addGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        addGroupLayout.setVerticalGroup(
            addGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addGroupLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(addGroup, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataGroup);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed
        jLabel2.setText("Edit Group");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addGroup);
        mainPanel.repaint();
        mainPanel.revalidate();  
        getDataTable();// TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        delData();  // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        jLabel2.setText("Add Group");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addGroup);
        mainPanel.repaint();
        mainPanel.revalidate();
        resetForm();
    }//GEN-LAST:event_addBtnActionPerformed

    private void dataDistributorTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataDistributorTableFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_dataDistributorTableFocusGained

    private void dataDistributorTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataDistributorTableFocusLost
       
    }//GEN-LAST:event_dataDistributorTableFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jLabel2.getText().equals("Add Group")){
             saveData(); // TODO add your handling code here:
       }else if(jLabel2.getText().equals("Edit Group")){
            updateData();
           
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGroupActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addGroup;
    private javax.swing.JTable dataDistributorTable;
    private javax.swing.JPanel dataGroup;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tfGroup;
    private javax.swing.JTextField tfId;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        List<Model_Group> list = service.getData();
        tblMod.setData(list);
        mainPanel.revalidate();
    }

    private void getDataTable() {
        int row = dataDistributorTable.getSelectedRow();
        tfId.setText(dataDistributorTable.getModel().getValueAt(row, 1).toString());
        tfGroup.setText(dataDistributorTable.getModel().getValueAt(row, 2).toString());
    }

    private void delData() {
        int index = dataDistributorTable.getSelectedRow();
        if(index!=-1){
            Model_Group modDis = tblMod.getData(dataDistributorTable.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(modDis);
                tblMod.deleteData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }
    private void saveData() {
        if(inputValidation()){
            
            String dn = tfId.getText();
            String l = tfGroup.getText();
            
            
            Model_Group md = new Model_Group();
            md.setId_group("G-"+getAwalTengahAkhir(l));
            md.setGroup_name(l);  
            md.setStatus_active("1");
            md.setCreated_date(getCurrentDateTime());
            md.setUpdated_date(getCurrentDateTime());
            md.setUpdated_by("Super Admin");
            md.setCreated_by("Super Admin");
//            System.out.print((String)generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            service.addData(md);
            tblMod.addData(md);
            resetForm();
            loadData();
            showPanel();
        }
    }
    public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }
    public String getFourthChar(String text) {
        if (text != null && text.length() >= 4) {
          return String.valueOf(text.charAt(3)); // huruf ke-4 (indeks ke-3)
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
        }
    }

    private void updateData() {
        int index = dataDistributorTable.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
            String id = dataDistributorTable.getModel().getValueAt(index, 1).toString();
            String dn = tfId.getText();
            String l = tfGroup.getText();
            
            
            Model_Group md = new Model_Group();
            md.setId_group(id);
            md.setGroup_name(l);                        
            md.setStatus_active("1");
            md.setUpdated_date(getCurrentDateTime());
            md.setUpdated_by("Super Admin");
            service.updateData(md);
            tblMod.updateData(index, md);
            loadData();
            showPanel();      
               
                
            }
        }
    }
    private boolean inputValidation() {
        boolean result = false;
         if(tfGroup.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Group is Required!");
        }else{
            result = true;
        }
        return result;
    }

    private String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }

    private void resetForm() {
        tfId.setText("");
        tfGroup.setText("");
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Mst_Group());
        mainPanel.repaint();
        mainPanel.revalidate();
    }
   public static String getAwalTengahAkhir(String input) {
        if (input == null || input.isEmpty()) {
            return "";
        }

        input = input.toUpperCase();
        int length = input.length();

        if (length == 1) {
            return input + input + input;
        }

        if (length == 2) {
            return "" + input.charAt(0) + input.charAt(1) + input.charAt(1);
        }

        char awal = input.charAt(0);
        char tengah = input.charAt(length / 2);
        char akhir = input.charAt(length - 1);

        // Validasi: jika huruf tengah adalah spasi, ganti dengan 'X'
        if (tengah == ' ') {
            tengah = 'X';
        }

        return "" + awal + tengah + akhir;
    }
}