/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import dao.DAO_Menu;
import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Menu;
import service.Service_Menu;
import tablemodel.TabMod_Menu;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author rafii
 */
public class Mst_Menu extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private Service_Menu service = (Service_Menu) new DAO_Menu();
    private TabMod_Menu tblMod = new TabMod_Menu();
    
    public Mst_Menu() {
        initComponents();
        dataMenuTable.setModel(tblMod);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataMenuTable = new javax.swing.JTable();
        addMenu = new javax.swing.JPanel();
        titleMenu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Namemenu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        saveAddMenu = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Menu");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn);

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(111, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(111, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(111, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn);

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataMenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataMenuTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataMenuTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataMenuTable.getTableHeader().setReorderingAllowed(false);
        dataMenuTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataMenuTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataMenuTableFocusLost(evt);
            }
        });
        dataMenuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMenuTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataMenuTable);

        javax.swing.GroupLayout dataMenuLayout = new javax.swing.GroupLayout(dataMenu);
        dataMenu.setLayout(dataMenuLayout);
        dataMenuLayout.setHorizontalGroup(
            dataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataMenuLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(dataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataMenuLayout.setVerticalGroup(
            dataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataMenu, "card2");

        addMenu.setBackground(new java.awt.Color(255, 255, 255));

        titleMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMenu.setText("Add Menu");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Namemenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Namemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamemenuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 17)); // NOI18N
        jLabel4.setText("Name Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Namemenu, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Namemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        saveAddMenu.setBackground(new java.awt.Color(102, 255, 0));
        saveAddMenu.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        saveAddMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        saveAddMenu.setText("Save");
        saveAddMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddMenuActionPerformed(evt);
            }
        });
        jPanel2.add(saveAddMenu);

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton5.setText("Cancel");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        javax.swing.GroupLayout addMenuLayout = new javax.swing.GroupLayout(addMenu);
        addMenu.setLayout(addMenuLayout);
        addMenuLayout.setHorizontalGroup(
            addMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addMenuLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(addMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        addMenuLayout.setVerticalGroup(
            addMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMenuLayout.createSequentialGroup()
                .addComponent(titleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(addMenu, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataMenu);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void saveAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddMenuActionPerformed
       if(titleMenu.getText().equals("Add Menu")){
            saveData();
       }else if(titleMenu.getText().equals("Edit Menu")){
            updateData();
       }
    }//GEN-LAST:event_saveAddMenuActionPerformed

    private void dataMenuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMenuTableMouseClicked

    }//GEN-LAST:event_dataMenuTableMouseClicked

    private void dataMenuTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataMenuTableFocusLost

    }//GEN-LAST:event_dataMenuTableFocusLost

    private void dataMenuTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataMenuTableFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_dataMenuTableFocusGained

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        titleMenu.setText("Edit Menu");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addMenu);
        mainPanel.repaint();
        mainPanel.revalidate();
        getDataTable();
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        delData();
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        titleMenu.setText("Add Menu");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addMenu);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_addBtnActionPerformed

    private void NamemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamemenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamemenuActionPerformed
    private void saveData() {
        if(inputValidation()){
            
            String ps = Namemenu.getText();
            
            String pv = (String) Namemenu.getText();
            
            Model_Menu mp = new Model_Menu();
            mp.setId_menu(generateSmartId(getFourthChar((String) pv)+"-"));
            mp.setName_menu(ps);
           
            mp.setSts_active("1");
            mp.setCreated_date(getCurrentDateTime());
            mp.setUpdated_date(getCurrentDateTime());
            mp.setUpdated_by("Admin");
            mp.setCreated_by("Admin");
//            System.out.print((String)generateSmartId(getFourthChar((String) cbVendor.getSelectedItem())+"-"));
            service.addData(mp);
            tblMod.addData(mp);
            resetForm();
            loadData();
            showPanel();
        }
    }
    public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }
    public String getFourthChar(String text) {
        if (text != null && text.length() >= 4) {
          return String.valueOf(text.charAt(3)); // huruf ke-4 (indeks ke-3)
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
        }
    }
    private boolean inputValidation(){
        boolean result = false;
        if(Namemenu.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Name Menu is Required!");
        }else{
            result = true;
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Namemenu;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addMenu;
    private javax.swing.JPanel dataMenu;
    private javax.swing.JTable dataMenuTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton saveAddMenu;
    private javax.swing.JLabel titleMenu;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        List<Model_Menu> list = service.getData();
        tblMod.setData(list);
        mainPanel.revalidate();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- Choose Vendor --");

    // Tambahkan nama vendor ke model
//    for (Model_Menu menu : listMenu) {
//        model.addElement(menu.getMovr().getVendor_name().toString());
//    }
    
    // Set model ke JComboBox
//    cbVendor.setModel(model);
    }
    public String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }

    private void resetForm() {
        
        Namemenu.setText("");
//        cbVendor.setSelectedIndex(0);
//        cbPm.setSelectedIndex(0);
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Mst_Menu());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void getDataTable() {
        int row = dataMenuTable.getSelectedRow();
        Namemenu.setText(dataMenuTable.getModel().getValueAt(row, 2).toString());
//        cbVendor.setSelectedItem((String) dataMenuTable.getModel().getValueAt(row, 5).toString());
//        cbPm.setSelectedItem((String) dataMenuTable.getModel().getValueAt(row, 2).toString());
        
    }
    
    private void updateData() {
        int index = dataMenuTable.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
                String ip = dataMenuTable.getModel().getValueAt(index, 1).toString();
//                String pn = Idmenu.getText();
                String ps = Namemenu.getText();
                
                Model_Menu mp = new Model_Menu();
                
               
                mp.setId_menu(ip);
                mp.setName_menu(ps);
               
                mp.setUpdated_date(getCurrentDateTime());
                mp.setUpdated_by("Admin");
                service.updateData(mp);
                tblMod.updateData(index, mp);
                loadData();
                showPanel();
            }
        }
    }

    private void delData() {
        int index = dataMenuTable.getSelectedRow();
        if(index!=-1){
            Model_Menu modPro = tblMod.getData(dataMenuTable.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service.deleteData(modPro);
                tblMod.deleteData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }
    
}
