/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import service.NumericDocumentFilter;
import config.Koneksi;
import dao.DAO_Cart_Incoming;
import dao.DAO_Cart_Outgoing;
import dao.DAO_Detail_Incoming;
import dao.DAO_Detail_Outgoing;
import dao.DAO_Incoming;
import dao.DAO_Outgoing;
import dao.DAO_Project;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Project;
import model.Model_Vendor;
import service.Service_Project;
import tablemodel.TabMod_Project;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.TableModel;
import javax.swing.text.AbstractDocument;
import main.Menu_utama;
import model.Model_Cart_Incoming;
import model.Model_Cart_Outgoing;
import model.Model_Detail_Incoming;
import model.Model_Detail_Outgoing;
import model.Model_Distributor;
import model.Model_Incoming;
import model.Model_Item;
import model.Model_Karyawan;
import model.Model_Outgoing;
import model.Model_Type;
import service.Service_Cart_Incoming;
import service.Service_Cart_Outgoing;
import service.Service_Detail_Incoming;
import service.Service_Detail_Outgoing;
import service.Service_Incoming;
import service.Service_Outgoing;
import tablemodel.TabMod_Cart_Incoming;
import tablemodel.TabMod_Cart_Outgoing;
import tablemodel.TabMod_Detail_Incoming;
import tablemodel.TabMod_Detail_Outgoing;
import tablemodel.TabMod_Incoming;
import tablemodel.TabMod_Outgoing;


/**
 *
 * @author rafii
 */
public class Tx_Outgoing extends javax.swing.JPanel {

    /**
     * Creates new form Mst_Item
     */
    private Service_Outgoing serviceOut = (Service_Outgoing) new DAO_Outgoing();
    private Service_Detail_Outgoing serviceDetOut = (Service_Detail_Outgoing) new DAO_Detail_Outgoing();
    private Service_Cart_Outgoing serviceCartOut = (Service_Cart_Outgoing) new DAO_Cart_Outgoing();
    
    private TabMod_Outgoing tblModOut = new TabMod_Outgoing();
    private TabMod_Detail_Outgoing tblModDetOut = new TabMod_Detail_Outgoing();
    private TabMod_Cart_Outgoing tblModCartOut = new TabMod_Cart_Outgoing();
    
    private final String id;
    public Tx_Outgoing(String id) {
        initComponents();
        setupSubtotalUpdater();
        ((AbstractDocument) tfQuantity.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        tbl_out.setModel(tblModOut);
        tbl_detail.setModel(tblModDetOut);
        tblCart.setModel(tblModCartOut);
        loadData();
        pnDetail.setVisible(false);
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataOutgoing = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_out = new javax.swing.JTable();
        pnDetail = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_detail = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        addOutgoing = new javax.swing.JPanel();
        titleProject = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNoIncoming = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tfIdDistributor = new javax.swing.JTextField();
        bDistributor = new javax.swing.JButton();
        tfDistributorName = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfType = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfItem = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        tfQuantity = new javax.swing.JTextField();
        tfUnit = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        tfIdItem = new javax.swing.JTextField();
        bItem = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfBrand = new javax.swing.JTextField();
        bAddCart = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        saveAddProject = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        bUpdCart = new javax.swing.JButton();
        bDelCart = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataOutgoing.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Transaction Outgoing");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel6.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 125, -1));

        delBtn.setBackground(new java.awt.Color(255, 0, 51));
        delBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-delete.png"))); // NOI18N
        delBtn.setText("Delete");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setEnabled(false);
        delBtn.setMaximumSize(new java.awt.Dimension(95, 33));
        delBtn.setMinimumSize(new java.awt.Dimension(95, 33));
        delBtn.setPreferredSize(new java.awt.Dimension(95, 33));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jPanel6.add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 0, 125, -1));

        updBtn.setBackground(new java.awt.Color(255, 255, 0));
        updBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        updBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-edit.png"))); // NOI18N
        updBtn.setText("Update");
        updBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updBtn.setEnabled(false);
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });
        jPanel6.add(updBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_out.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_out.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_out.getTableHeader().setReorderingAllowed(false);
        tbl_out.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbl_outFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbl_outFocusLost(evt);
            }
        });
        tbl_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_outMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_out);

        pnDetail.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Detail Outgoing");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_detail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_detail.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_detail.getTableHeader().setReorderingAllowed(false);
        tbl_detail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbl_detailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbl_detailFocusLost(evt);
            }
        });
        tbl_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_detail);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataOutgoingLayout = new javax.swing.GroupLayout(dataOutgoing);
        dataOutgoing.setLayout(dataOutgoingLayout);
        dataOutgoingLayout.setHorizontalGroup(
            dataOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dataOutgoingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataOutgoingLayout.createSequentialGroup()
                        .addGroup(dataOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(579, 579, 579))
                    .addGroup(dataOutgoingLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        dataOutgoingLayout.setVerticalGroup(
            dataOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataOutgoingLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataOutgoing, "card2");

        addOutgoing.setBackground(new java.awt.Color(255, 255, 255));

        titleProject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleProject.setText("Add Outgoing");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No Outgoing");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");

        tfNoIncoming.setEnabled(false);
        tfNoIncoming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoIncomingActionPerformed(evt);
            }
        });

        tfDate.setEnabled(false);
        tfDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNoIncoming)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDate)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoIncoming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 0, 51));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Project");

        jLabel15.setBackground(new java.awt.Color(255, 0, 51));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Project Name");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("ID Project");

        tfIdDistributor.setBackground(new java.awt.Color(240, 240, 240));
        tfIdDistributor.setEnabled(false);
        tfIdDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdDistributorActionPerformed(evt);
            }
        });

        bDistributor.setText("...");
        bDistributor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDistributorActionPerformed(evt);
            }
        });

        tfDistributorName.setEnabled(false);
        tfDistributorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDistributorNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(tfIdDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(tfDistributorName))
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel15))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfIdDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDistributorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 0, 51));

        jLabel19.setBackground(new java.awt.Color(255, 0, 51));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Items");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID Items");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Type");

        tfType.setText("jTextField12");
        tfType.setEnabled(false);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Item Name");

        tfItem.setText("jTextField12");
        tfItem.setEnabled(false);

        jPanel11.setBackground(new java.awt.Color(255, 0, 51));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Quantity");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 5, new java.awt.Color(255, 0, 51)));
        jPanel11.add(jLabel24);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Unit");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(255, 0, 51)));
        jPanel11.add(jLabel23);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        tfQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 5, new java.awt.Color(255, 0, 51)));
        tfQuantity.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfQuantityInputMethodTextChanged(evt);
            }
        });
        tfQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantityActionPerformed(evt);
            }
        });
        tfQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQuantityKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantityKeyTyped(evt);
            }
        });
        jPanel12.add(tfQuantity);

        tfUnit.setText("jTextField16");
        tfUnit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(255, 0, 51)));
        tfUnit.setEnabled(false);
        jPanel12.add(tfUnit);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        tfIdItem.setText("it");
        tfIdItem.setEnabled(false);
        tfIdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdItemActionPerformed(evt);
            }
        });
        jPanel13.add(tfIdItem);

        bItem.setText("...");
        bItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bItemActionPerformed(evt);
            }
        });
        jPanel13.add(bItem);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Brand");

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        tfBrand.setText("jTextField12");
        tfBrand.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 5, new java.awt.Color(255, 0, 51)));
        tfBrand.setEnabled(false);
        jPanel1.add(tfBrand);

        bAddCart.setText("Add To Cart");
        bAddCart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 0, 51)));
        bAddCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCartActionPerformed(evt);
            }
        });
        jPanel1.add(bAddCart);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfType)
                            .addComponent(tfItem)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton5.setText(" Cancel");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        saveAddProject.setBackground(new java.awt.Color(102, 255, 0));
        saveAddProject.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        saveAddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checklist.png"))); // NOI18N
        saveAddProject.setText(" Save");
        saveAddProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAddProjectActionPerformed(evt);
            }
        });

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCart);

        bUpdCart.setBackground(new java.awt.Color(255, 255, 0));
        bUpdCart.setText("Update Item");
        bUpdCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUpdCart.setEnabled(false);
        bUpdCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdCartActionPerformed(evt);
            }
        });

        bDelCart.setBackground(new java.awt.Color(255, 0, 51));
        bDelCart.setText("Delete Item");
        bDelCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDelCart.setEnabled(false);
        bDelCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addOutgoingLayout = new javax.swing.GroupLayout(addOutgoing);
        addOutgoing.setLayout(addOutgoingLayout);
        addOutgoingLayout.setHorizontalGroup(
            addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOutgoingLayout.createSequentialGroup()
                .addGroup(addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addOutgoingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addOutgoingLayout.createSequentialGroup()
                                .addComponent(saveAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titleProject, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addGroup(addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOutgoingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(addOutgoingLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bUpdCart, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bDelCart, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        addOutgoingLayout.setVerticalGroup(
            addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOutgoingLayout.createSequentialGroup()
                .addComponent(titleProject, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(saveAddProject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addOutgoingLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bUpdCart)
                            .addComponent(bDelCart))))
                .addContainerGap())
        );

        mainPanel.add(addOutgoing, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(dataOutgoing);
        mainPanel.repaint();
        mainPanel.revalidate();
        serviceCartOut.delCart();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void saveAddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddProjectActionPerformed
       if(titleProject.getText().equals("Add Outgoing")){
            saveData();
       }else if(titleProject.getText().equals("Edit Outgoing")){
//            updateData();
       }
    }//GEN-LAST:event_saveAddProjectActionPerformed

    private void tbl_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_outMouseClicked
        int row = tbl_out.getSelectedRow();
        String id = tbl_out.getValueAt(row,0).toString();
        pnDetail.setVisible(true);  
        List<Model_Detail_Outgoing> list = serviceDetOut.getData(id);
        tblModDetOut.setData(list);
        delBtn.setVisible(true);
    }//GEN-LAST:event_tbl_outMouseClicked

    private void tbl_outFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_outFocusLost

    }//GEN-LAST:event_tbl_outFocusLost

    private void tbl_outFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_outFocusGained
        delBtn.setEnabled(true);
        updBtn.setEnabled(true);
    }//GEN-LAST:event_tbl_outFocusGained

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        titleProject.setText("Edit Incoming");
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addOutgoing);
        mainPanel.repaint();
        mainPanel.revalidate();
        
//        getDataTable();
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        delData();
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(addOutgoing);
        mainPanel.repaint();
        mainPanel.revalidate();
        resetForm();
        showData();
        bDistributor.setEnabled(true);
        loadDataCartIn();
        bUpdCart.setEnabled(false);
        bDelCart.setEnabled(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void tbl_detailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_detailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_detailFocusGained

    private void tbl_detailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_detailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_detailFocusLost

    private void tbl_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_detailMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        pnDetail.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tfDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDateActionPerformed

    private void tfNoIncomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoIncomingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoIncomingActionPerformed

    private void tfIdDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdDistributorActionPerformed

    private void tfDistributorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDistributorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDistributorNameActionPerformed

    private void bDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDistributorActionPerformed
     Data_Project datDis = new Data_Project(null, true);
        datDis.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            // Kode ini akan dijalankan setelah dialog ditutup dan di-dispose
            if (datDis.model.getProject_name() != null && !datDis.model.getProject_name().isEmpty()) {
                tfIdDistributor.setText(datDis.model.getId_project());
                tfDistributorName.setText(datDis.model.getProject_name());
                resetFormItem();
                bDistributor.setEnabled(false);
            } else {
                System.out.println("Tidak ada distributor dipilih.");
            }
            bItem.requestFocus();

        }
    });
    datDis.setVisible(true);
    }//GEN-LAST:event_bDistributorActionPerformed

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
        int row = tblCart.getSelectedRow();
        tfIdItem.setText(tblCart.getModel().getValueAt(row, 1).toString());
        tfItem.setText(tblCart.getModel().getValueAt(row, 4).toString());
        tfType.setText(tblCart.getModel().getValueAt(row, 3).toString());
        tfQuantity.setText(tblCart.getModel().getValueAt(row,5).toString());
        tfUnit.setText(tblCart.getModel().getValueAt(row, 6).toString());
        tfBrand.setText(tblCart.getModel().getValueAt(row, 7).toString());
        bUpdCart.setEnabled(true);
        bDelCart.setEnabled(true);
        bAddCart.setEnabled(false);
    }//GEN-LAST:event_tblCartMouseClicked

    private void bDelCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelCartActionPerformed
        int index = tblCart.getSelectedRow();
        if(index!=-1){
            Model_Cart_Outgoing mci = tblModCartOut.getData(tblCart.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                serviceCartOut.deleteData(tblCart.getModel().getValueAt(index, 1).toString());
                tblModCartOut.deleteData(index);
                List<Model_Cart_Outgoing> list = serviceCartOut.getData();
                tblModCartOut.setData(list);
                resetFormItem();
                bDelCart.setEnabled(false);
                bUpdCart.setEnabled(false);
                bAddCart.setEnabled(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }//GEN-LAST:event_bDelCartActionPerformed

    private void bUpdCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdCartActionPerformed
            updateCart();
    }//GEN-LAST:event_bUpdCartActionPerformed

    private void bAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCartActionPerformed
        addToCart();
    }//GEN-LAST:event_bAddCartActionPerformed

    private void bItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bItemActionPerformed
        String id = tfIdDistributor.getText();
        Data_Item datItem = new Data_Item(null, true,id);
        bUpdCart.setEnabled(false);
        bDelCart.setEnabled(false);
        bAddCart.setEnabled(true);
        datItem.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Kode ini akan dijalankan setelah dialog ditutup dan di-dispose
                if (datItem.model.getItems_name() != null && !datItem.model.getItems_name().isEmpty()) {
                    tfIdItem.setText(datItem.model.getId_items());
                    tfItem.setText(datItem.model.getItems_name());
                    tfType.setText(datItem.model.getMoty().getType_name());
                    tfUnit.setText(datItem.model.getUnit());
                    tfBrand.setText(datItem.model.getBrand());
                    tfQuantity.setText("1");
                }
                //            bItem.requestFocus();
            }
        });
        datItem.setVisible(true);
    }//GEN-LAST:event_bItemActionPerformed

    private void tfIdItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdItemActionPerformed

    private void tfQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantityKeyTyped

    }//GEN-LAST:event_tfQuantityKeyTyped

    private void tfQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantityKeyPressed

    }//GEN-LAST:event_tfQuantityKeyPressed

    private void tfQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantityActionPerformed

    }//GEN-LAST:event_tfQuantityActionPerformed

    private void tfQuantityInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfQuantityInputMethodTextChanged

    }//GEN-LAST:event_tfQuantityInputMethodTextChanged
    private void addToCart(){
        if(inputValidation()){
            String idIncoming = tfNoIncoming.getText();
            String idDis = tfIdDistributor.getText();
            String disName = tfDistributorName.getText();
            String idItem = tfIdItem.getText();
            String itemName = tfItem.getText();
            String type = tfType.getText();
            String quantity = tfQuantity.getText();
            String unit = tfUnit.getText();
            String brand = tfBrand.getText();
            
            Model_Cart_Outgoing mci = new Model_Cart_Outgoing();
            Model_Outgoing min = new Model_Outgoing();
            Model_Detail_Outgoing mdi = new Model_Detail_Outgoing();
            Model_Item mi = new Model_Item();
            Model_Project md = new Model_Project();
            Model_Type mt = new Model_Type();
            min.setId_outgoing(idIncoming);
            mdi.setMoou(min);
            md.setId_project(idDis);
            md.setProject_name(disName);
            mi.setId_items(idItem);
            mi.setItems_name(itemName);
            mt.setType_name(type);
            mdi.setQuantity(quantity);
            mi.setUnit(unit);
            mi.setBrand(brand);
            mci.setModo(mdi);
            mci.setMopr(md);
            mci.setMoit(mi);
            mci.setMoty(mt);

            serviceCartOut.addData(mci);       
            resetFormItem();
            loadDataCartIn();
            }
    }
    private void saveData() {
        TableModel model = tblCart.getModel();
        if(tblCart.getRowCount()!=0){
                Model_Cart_Outgoing mci = new Model_Cart_Outgoing();
                Model_Outgoing min = new Model_Outgoing();
                Model_Detail_Outgoing mdi = new Model_Detail_Outgoing();
                Model_Item mi = new Model_Item();
                Model_Project md = new Model_Project();
                Model_Type mt = new Model_Type();
                Model_Karyawan mk = new Model_Karyawan();
            int rowCount = tblCart.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                String idIncoming       = model.getValueAt(i, 0).toString();
                String idItem           = model.getValueAt(i, 1).toString();
                String idDis            = tfIdDistributor.getText();
                String date             = tfDate.getText();
                String disName          = model.getValueAt(i, 2).toString();
                String type             = model.getValueAt(i, 3).toString();
                String itemName         = model.getValueAt(i, 4).toString();
                String quantity         = model.getValueAt(i, 5).toString();
                String unit             = model.getValueAt(i, 6).toString();
                String brand            = model.getValueAt(i, 7).toString();

                min.setId_outgoing(idIncoming);
                min.setTransaction_date(date);
                md.setId_project(idDis);
                md.setProject_name(disName);
                mi.setId_items(idItem);
                mi.setItems_name(itemName);
                mt.setType_name(type);
                mdi.setQuantity(quantity);
                mdi.setMoit(mi);
                serviceDetOut.useStock(mdi);
                mi.setUnit(unit);
                mi.setBrand(brand);
                mdi.setMoou(min);
                mci.setModo(mdi);
                mci.setMopr(md);
                mci.setMoit(mi);
                mci.setMoty(mt);
                serviceDetOut.addData(mci);
            }

            mk.setId_karyawan(id);
            mdi.setMokr(mk);
            mci.setModo(mdi);

            serviceOut.addData(mci);
            loadData();
            serviceCartOut.delCart();
            JOptionPane.showMessageDialog(null,"Success to add outgoing");
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();
            mainPanel.add(dataOutgoing);
            mainPanel.repaint();
            mainPanel.revalidate();
            
    }else{
            JOptionPane.showMessageDialog(
        null,
        "Failed to save data. Please add items to the cart first.",
        "Save Error",
        JOptionPane.ERROR_MESSAGE
    );
        }
    }
    public String getCurrentDateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return now.format(formatter);
    }
    public String getFourthChar(String text) {
        if (text != null && text.length() >= 4) {
          return String.valueOf(text.charAt(3)); // huruf ke-4 (indeks ke-3)
        } else {
           throw new IllegalArgumentException("String harus memiliki minimal 4 karakter.");
        }
    }
    private boolean inputValidation(){
        boolean result = false;
        if(tfIdDistributor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Project is Required!");
        }else if(tfIdItem.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Items is Required!");
        }else if(tfQuantity.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Quantity is Required!");
        }else{
            result = true;
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addOutgoing;
    private javax.swing.JButton bAddCart;
    private javax.swing.JButton bDelCart;
    private javax.swing.JButton bDistributor;
    private javax.swing.JButton bItem;
    private javax.swing.JButton bUpdCart;
    private javax.swing.JPanel dataOutgoing;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JButton saveAddProject;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tbl_detail;
    private javax.swing.JTable tbl_out;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfDistributorName;
    private javax.swing.JTextField tfIdDistributor;
    private javax.swing.JTextField tfIdItem;
    private javax.swing.JTextField tfItem;
    private javax.swing.JTextField tfNoIncoming;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfType;
    private javax.swing.JTextField tfUnit;
    private javax.swing.JLabel titleProject;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        delBtn.setVisible(false);
        updBtn.setVisible(false);
        List<Model_Outgoing> list = serviceOut.getData();
        tblModOut.setData(list);

    }
    public String generateSmartId(String prefix) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        int random = new Random().nextInt(9000) + 1000; // 4 digit random
        return prefix + date + random;
    }

    private void resetFormItem() {
        tfIdItem.setText("");
        tfItem.setText("");
        tfType.setText("");
        tfQuantity.setText("");
        tfUnit.setText("");
        tfBrand.setText("");
    }
        private void resetForm() {
        tfIdDistributor.setText("");
        tfDistributorName.setText("");
        tfNoIncoming.setText("");
        tfDate.setText("");
        resetFormItem();
    }

    private void showPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Tx_Outgoing(id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

//    private void getDataTable() {
//        int row = tbl_in.getSelectedRow();
//        ProjectName.setText(tbl_in.getModel().getValueAt(row, 3).toString());
//        ProjectSite.setText(tbl_in.getModel().getValueAt(row, 4).toString());
//        cbVendor.setSelectedItem((String) tbl_in.getModel().getValueAt(row, 5).toString());
//        cbPm.setSelectedItem((String) tbl_in.getModel().getValueAt(row, 2).toString());
//        
//    }
//    
//    private void updateData() {
//        int index = tbl_in.getSelectedRow();
//        if(index!=-1){
////            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
//            if(inputValidation()){
//                String ip = tbl_in.getModel().getValueAt(index, 1).toString();
//                String pn = ProjectName.getText();
//                String ps = ProjectSite.getText();
//                String pv = (String) cbVendor.getSelectedItem();
//                String pm = (String) cbPm.getSelectedItem();
//                Model_Vendor mv = new Model_Vendor();
//                Model_Project mp = new Model_Project();
//                
//                List<Model_Project> listVendor = service.getDataVendor();
//                for (Model_Project project : listVendor) {
//                    if(project.getMovr().getVendor_name().toString().equals(pv)){
//                        mv.setId_vendor(project.getMovr().getId_vendor().toString());
//                        mp.setMovr(mv);
//                       
//                        
//                    }
//                }
//                mp.setId_project(ip);
//                mp.setProject_manager(pm);
//                mp.setProject_name(pn);
//                mp.setProject_site(ps);
//                mp.setUpdated_date(getCurrentDateTime());
//                mp.setUpdated_by("Admin");
//                service.updateData(mp);
//                tblMod.updateData(index, mp);
//                loadData();
//                showPanel();
//            }
//        }
//    }

    private void delData() {
        int index = tbl_out.getSelectedRow();
        if(index!=-1){
            Model_Outgoing modIn = tblModOut.getData(tbl_out.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null,"Delete this Data?","Warning",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                serviceOut.delData(modIn);
                tblModOut.deleteData(index);
                loadData();
                resetForm();  
            }
        }else{
            JOptionPane.showMessageDialog(null, "No data selected. Please select a row to delete!");
        }
    }

    private void showData() {
        tfNoIncoming.setText(generateSmartId("OUT"));
        tfDate.setText(getCurrentDateTime());
    }


        private void updateCart() {
        int index = tblCart.getSelectedRow();
        if(index!=-1){
//            Model_Project modPro = tblMod.getData(dataProjectTable.convertRowIndexToModel(index));
            if(inputValidation()){
            String idItem = tblCart.getModel().getValueAt(index, 1).toString();
            String idIncoming = tfNoIncoming.getText();
            String idDis = tfIdDistributor.getText();
            String disName = tfDistributorName.getText();
            String itemName = tfItem.getText();
            String type = tfType.getText();
            String quantity = tfQuantity.getText();
            String unit = tfUnit.getText();
            String brand = tfBrand.getText();
            
            Model_Cart_Outgoing mci = new Model_Cart_Outgoing();
            Model_Outgoing min = new Model_Outgoing();
            Model_Detail_Outgoing mdi = new Model_Detail_Outgoing();
            Model_Item mi = new Model_Item();
            Model_Project md = new Model_Project();
            Model_Type mt = new Model_Type();
            min.setId_outgoing(idIncoming);
            mdi.setMoou(min);
            md.setId_project(idDis);
            md.setProject_name(disName);
            mi.setId_items(idItem);
            mi.setItems_name(itemName);
            mt.setType_name(type);
            mdi.setQuantity(quantity);
            mi.setUnit(unit);;
            mi.setBrand(brand);
            mci.setModo(mdi);
            mci.setMopr(md);
            mci.setMoit(mi);
            mci.setMoty(mt);
                serviceCartOut.updCart(mci);
                tblModCartOut.updateData(index, mci);
                loadDataCartIn();
                bAddCart.setEnabled(true);
                bUpdCart.setEnabled(false);
                bDelCart.setEnabled(false);
                resetFormItem();
//                showPanel();
            }
        }
    }

    private void loadDataCartIn() {
//        delBtn.setVisible(false);
//        updBtn.setVisible(false);
        List<Model_Cart_Outgoing> list = serviceCartOut.getData();
        
        tblModCartOut.setData(list);
    }
    private void setupSubtotalUpdater() {
    DocumentListener listener = new DocumentListener() {
        public void insertUpdate(DocumentEvent e) {
            updateSubtotal();
        }

        public void removeUpdate(DocumentEvent e) {
            updateSubtotal();
        }

        public void changedUpdate(DocumentEvent e) {
            updateSubtotal();
        }
    };

    tfQuantity.getDocument().addDocumentListener(listener);
}

private void updateSubtotal() {
    String qtyText = tfQuantity.getText().trim();

    if (!qtyText.isEmpty()) {
        try {
            int qty = Integer.parseInt(qtyText);
        } catch (NumberFormatException e) {

        }
    } else {
    }
}

}
