/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import dao.DAO_Reportincoming;
import dao.DAO_Reportitems;
import dao.DAO_Reportproject;
import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_Reportoutgoing;
import service.Service_Reportoutgoing;
import tablemodel.TabMod_Reportoutgoing;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import model.Model_Item;
import model.Model_Project;
import service.Service_Reportincoming;
import service.Service_Reportitems;
import service.Service_Reportproject;
import tablemodel.TabMod_Item;
import tablemodel.TabMod_Project;


/**
 *
 * @author rafii
 */
public class V_Reportitems extends javax.swing.JPanel {
    /**
     * Creates new form Mst_Item
     */
    
    private Service_Reportitems service = (Service_Reportitems) new DAO_Reportitems();
    private TabMod_Item tblMod = new TabMod_Item();
    public String nama;
    public V_Reportitems(String user) {
        initComponents();
        dataReportoutgoingTable.setModel(tblMod);
        this.nama=user;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataReportOutgoing = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataReportoutgoingTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataReportOutgoing.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Items Report");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        dataReportoutgoingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Type", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataReportoutgoingTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataReportoutgoingTable.setGridColor(new java.awt.Color(255, 255, 255));
        dataReportoutgoingTable.getTableHeader().setReorderingAllowed(false);
        dataReportoutgoingTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataReportoutgoingTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataReportoutgoingTableFocusLost(evt);
            }
        });
        dataReportoutgoingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataReportoutgoingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataReportoutgoingTable);

        jButton1.setText("Print");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Cable FO & Accessories", "Cable UTP & Accessories" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Type");

        javax.swing.GroupLayout dataReportOutgoingLayout = new javax.swing.GroupLayout(dataReportOutgoing);
        dataReportOutgoing.setLayout(dataReportOutgoingLayout);
        dataReportOutgoingLayout.setHorizontalGroup(
            dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataReportOutgoingLayout.createSequentialGroup()
                .addGroup(dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataReportOutgoingLayout.createSequentialGroup()
                        .addGroup(dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataReportOutgoingLayout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addGroup(dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)))
                            .addGroup(dataReportOutgoingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 263, Short.MAX_VALUE))
                    .addGroup(dataReportOutgoingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataReportOutgoingLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        dataReportOutgoingLayout.setVerticalGroup(
            dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataReportOutgoingLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataReportOutgoingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainPanel.add(dataReportOutgoing, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void dataReportoutgoingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataReportoutgoingTableMouseClicked

    }//GEN-LAST:event_dataReportoutgoingTableMouseClicked

    private void dataReportoutgoingTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataReportoutgoingTableFocusLost

    }//GEN-LAST:event_dataReportoutgoingTableFocusLost

    private void dataReportoutgoingTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataReportoutgoingTableFocusGained
        
    }//GEN-LAST:event_dataReportoutgoingTableFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str =(String) jComboBox1.getSelectedItem();
        if(str.contains("All")){
            service.Report(nama);
        }else{
            service.Report(nama,str);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                String str =(String) jComboBox1.getSelectedItem();
                if(str.contains("All")){
        List<Model_Item> list = service.getData();
        tblMod.setData(list);
        mainPanel.revalidate();
        }else{
        List<Model_Item> list = service.getData(str);
        tblMod.setData(list);
        mainPanel.revalidate();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataReportOutgoing;
    private javax.swing.JTable dataReportoutgoingTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

  private void loadData() {
        List<Model_Item> list = service.getData();
        tblMod.setData(list);
        mainPanel.revalidate();
        
    }
  
//  private void getDataTable() {
//        int row = dataVendorTable.getSelectedRow();
//        jTextField2.setText(dataVendorTable.getModel().getValueAt(row, 2).toString());
//        jTextField3.setText(dataVendorTable.getModel().getValueAt(row, 3).toString());
//        jTextField4.setText(dataVendorTable.getModel().getValueAt(row, 4).toString());
//        jTextField6.setText(dataVendorTable.getModel().getValueAt(row, 5).toString());
//    }
    
        
}
