/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import view.Mst_Distributor;
import view.Mst_Group;
import view.Mst_Item;
import view.Mst_Karyawan;
import view.Mst_Menu;
import view.Mst_Project;
import view.Mst_User;
import view.Mst_UserGroup;
import view.Mst_Vendor;
import view.Tx_Incoming;
import view.V_Reportincoming;
import view.V_Reportoutgoing;
import view.Tx_Outgoing;
import view.V_Reportitems;
import view.V_Reportproject;
import view.V_Reportuser;

/**
 *
 * @author rafii
 */
public class Menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_dashboard

     */
    private String idKry;

    public String getIdKry() {
        return idKry;
    }

    public void setIdKry(String idKry) {
        this.idKry = idKry;
    }
    public static String id,name,groupName,gender;
    public Menu_utama(String id, String name,String groupName,String gender ) {
        initComponents();
        this.id=id;
        this.name=name;
        this.groupName=groupName;
        this.gender=gender;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        execute();

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JPanel();
        pUser = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        nameUser = new javax.swing.JLabel();
        groupNameUser = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_navbar.setBackground(new java.awt.Color(255, 0, 51));
        pn_navbar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 51)));
        pn_navbar.setPreferredSize(new java.awt.Dimension(1104, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_PADICON.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTORY STORAGE APPLICATION");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 412));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new javax.swing.BoxLayout(menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menu);

        pUser.setBackground(new java.awt.Color(255, 255, 255));

        iconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/woman.png"))); // NOI18N

        nameUser.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        nameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameUser.setText("Muhammad Abdurrafi");

        groupNameUser.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        groupNameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupNameUser.setText("Super Admin");

        javax.swing.GroupLayout pUserLayout = new javax.swing.GroupLayout(pUser);
        pUser.setLayout(pUserLayout);
        pUserLayout.setHorizontalGroup(
            pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(groupNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pUserLayout.setVerticalGroup(
            pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserLayout.createSequentialGroup()
                .addComponent(iconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupNameUser))
        );

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sidebarLayout.createSequentialGroup()
                .addComponent(pUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(255, 0, 51)));
        pn_main.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1126, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_main.removeAll();
        pn_main.add(new content_bg());
        pn_main.repaint();
        pn_main.revalidate();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_utama(id,name,groupName,gender).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupNameUser;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nameUser;
    private javax.swing.JPanel pUser;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    // End of variables declaration//GEN-END:variables

     private void execute() {
//        System.out.println(id+name+groupName);
        ImageIcon iconHome = new ImageIcon(getClass().getResource("/img/house-chimney.png"));
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/img/master.png"));
        ImageIcon iconMasterData = new ImageIcon(getClass().getResource("/img/data_master.png"));
        ImageIcon iconTransaction = new ImageIcon(getClass().getResource("/img/IconTransaction.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/img/report.png"));
        ImageIcon iconMan = new ImageIcon(getClass().getResource("/img/man.png"));
        ImageIcon iconWoman = new ImageIcon(getClass().getResource("/img/woman.png"));
        ImageIcon iconSubT = new ImageIcon(getClass().getResource("/img/subTransaction.png"));
        ImageIcon iconAdministrator = new ImageIcon(getClass().getResource("/img/administrator.png"));
        ImageIcon iconSubA = new ImageIcon(getClass().getResource("/img/subAdministrator.png"));
        ImageIcon iconSubR = new ImageIcon(getClass().getResource("/img/subReport.png"));

        Menu_item adm1 = new Menu_item(null,true,iconSubA,"Users", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_User());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
        Menu_item adm2 = new Menu_item(null,true,iconMasterData,"Menu", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Menu());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
        Menu_item adm3 = new Menu_item(null,true,iconSubA,"Group", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Group());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
        Menu_item adm4 = new Menu_item(null,true,iconMasterData,"User Group", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_UserGroup());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });

        Menu_item master1 = new Menu_item(null,true,iconMasterData,"Items", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Item());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        Menu_item master2 = new Menu_item(null,true,iconMasterData,"Distributor", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Distributor());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        Menu_item master3 = new Menu_item(null,true,iconMasterData,"Karyawan", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Karyawan());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        Menu_item master4 = new Menu_item(null,true,iconMasterData,"Vendor", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Vendor());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        Menu_item master5 = new Menu_item(null,true,iconMasterData,"Project", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Mst_Project());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
        Menu_item transaction1 = new Menu_item(null,true,iconSubT,"Incoming", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Tx_Incoming(id));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        Menu_item transaction2 = new Menu_item(null,true,iconSubT,"Outgoing", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new Tx_Outgoing(id));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
        Menu_item report1 = new Menu_item(null,true,iconSubR,"Incoming Report", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new V_Reportincoming(name));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
         Menu_item report2 = new Menu_item(null,true,iconSubR,"Outgoing Report", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new V_Reportoutgoing(name));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
            Menu_item report3 = new Menu_item(null,true,iconSubR,"Project Report", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new V_Reportproject(name));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
            Menu_item report4 = new Menu_item(null,true,iconSubR,"Items Report", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new V_Reportitems(name));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });            
            Menu_item report5 = new Menu_item(null,true,iconSubR,"Users Report", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new V_Reportuser(name));
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        
        Menu_item menuHome = new Menu_item(iconHome,false,null,"Home", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                pn_main.removeAll();
                pn_main.add(new content_bg());
                pn_main.repaint();
                pn_main.revalidate();
            }
        });
        Menu_item administrator = new Menu_item(iconAdministrator,false,null,"Administrator", null,adm1,adm3);
        Menu_item menuMaster = new Menu_item(iconMaster,false,null,"Master", null,master1,master2,master3,master4,master5);
        Menu_item menuTransaction = new Menu_item(iconTransaction,false,null,"Transaction", null,transaction1,transaction2);
        Menu_item menuReport = new Menu_item(iconReport,false,null,"Reports", null,report4,report3,report1,report2,report5);
        if(groupName.contains("Super Admin")){
            addMenu(menuHome,administrator,menuMaster,menuTransaction,menuReport);    
        }else if(groupName.contains("Admin")){
            addMenu(menuHome,menuMaster,menuTransaction,menuReport);
        }else{
            addMenu(menuHome,menuTransaction,menuReport);
        }
        if(gender.equals("Male")){
            iconUser.setIcon(iconMan);
        }else if(gender.equals("Female")){
            iconUser.setIcon(iconWoman);
        }
        nameUser.setText(name);
        groupNameUser.setText(groupName);

        
    }
    
    private void addMenu(Menu_item...menu){
        for(int i=0;i<menu.length;i++){
            this.menu.add(menu[i]);
            ArrayList<Menu_item> subMenu=menu[i].getSubMenu();
            for (Menu_item m: subMenu){
                addMenu(m);
            }
        }
        this.menu.revalidate();
    }
}
